# Generated by Django 4.0.3 on 2022-04-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='make',
            name='photo',
            field=models.CharField(default='https://images.unsplash.com/photo-1580836618305-605c32623ae0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=435&q=80', max_length=255),
        ),
    ]
