# Generated by Django 4.0.3 on 2022-03-20 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.country'),
        ),
    ]
