# Generated by Django 4.0.3 on 2022-03-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='reports',
            old_name='user_id',
            new_name='user',
        ),
    ]
