# Generated by Django 4.0.3 on 2022-03-20 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_alter_reports_user_alter_userinfo_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='reported_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to='users.userinfo'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_reported', to='users.userinfo'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
