# Generated by Django 4.0.3 on 2022-04-03 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_transaction_seller_alter_transaction_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='buyer',
        ),
    ]
